/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.67
 * Generated at: 2022-11-10 01:24:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Spring/Teamproject/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/tourproject/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1668042832177L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"en\">\n");
      out.write("    <head>\n");
      out.write("        <meta charset=\"utf-8\" />\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1, shrink-to-fit=no\" />\n");
      out.write("        <meta name=\"description\" content=\"\" />\n");
      out.write("        <meta name=\"author\" content=\"\" />\n");
      out.write("        <title>Blog Home - Start Bootstrap Template</title>\n");
      out.write("        <!-- Favicon-->\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"/resources/templates/assets/favicon.ico\" />\n");
      out.write("        <!-- Core theme CSS (includes Bootstrap)-->\n");
      out.write("        <link href=\"/resources/templates/css/styles.css\" rel=\"stylesheet\" />\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- Responsive navbar-->\n");
      out.write("        <nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <a class=\"navbar-brand\" href=\"#!\">Start Bootstrap</a>\n");
      out.write("                <button class=\"navbar-toggler\" type=\"button\" data-bs-toggle=\"collapse\" data-bs-target=\"#navbarSupportedContent\" aria-controls=\"navbarSupportedContent\" aria-expanded=\"false\" aria-label=\"Toggle navigation\"><span class=\"navbar-toggler-icon\"></span></button>\n");
      out.write("                <div class=\"collapse navbar-collapse\" id=\"navbarSupportedContent\">\n");
      out.write("                    <ul class=\"navbar-nav ms-auto mb-2 mb-lg-0\">\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#\">Home</a></li>\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\">About</a></li>\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#!\">Contact</a></li>\n");
      out.write("                        <li class=\"nav-item\"><a class=\"nav-link active\" aria-current=\"page\" href=\"#\">Blog</a></li>\n");
      out.write("                    </ul>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </nav>\n");
      out.write("        <!-- Page header with logo and tagline-->\n");
      out.write("        <header class=\"py-5 bg-light border-bottom mb-4\">\n");
      out.write("            <div class=\"container\">\n");
      out.write("                <div class=\"text-center my-5\">\n");
      out.write("                    <h1 class=\"fw-bolder\">Welcome to Blog Home!</h1>\n");
      out.write("                    <p class=\"lead mb-0\">A Bootstrap 5 starter layout for your next blog homepage</p>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </header>\n");
      out.write("        <!-- Page content-->\n");
      out.write("        <div class=\"container\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <!-- Blog entries-->\n");
      out.write("                <div class=\"col-lg-8\">\n");
      out.write("                    <!-- Featured blog post-->\n");
      out.write("                    <div class=\"card mb-4\">\n");
      out.write("                        <a href=\"/info\"><img class=\"card-img-top\" src=\"https://dummyimage.com/850x350/dee2e6/6c757d.jpg\" alt=\"...\" /></a>\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <div class=\"small text-muted\">January 1, 2022</div>\n");
      out.write("                            <h2 class=\"card-title\">Featured Post Title</h2>\n");
      out.write("                            <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam. Dicta expedita corporis animi vero voluptate voluptatibus possimus, veniam magni quis!</p>\n");
      out.write("                            <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Nested row for non-featured blog posts-->\n");
      out.write("                    <div class=\"row\">\n");
      out.write("                        <div class=\"col-lg-6\">\n");
      out.write("                            <!-- Blog post-->\n");
      out.write("                            <div class=\"card mb-4\">\n");
      out.write("                                <a href=\"#!\"><img class=\"card-img-top\" src=\"https://dummyimage.com/700x350/dee2e6/6c757d.jpg\" alt=\"...\" /></a>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"small text-muted\">January 1, 2022</div>\n");
      out.write("                                    <h2 class=\"card-title h4\">Post Title</h2>\n");
      out.write("                                    <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>\n");
      out.write("                                    <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Blog post-->\n");
      out.write("                            <div class=\"card mb-4\">\n");
      out.write("                                <a href=\"#!\"><img class=\"card-img-top\" src=\"https://dummyimage.com/700x350/dee2e6/6c757d.jpg\" alt=\"...\" /></a>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"small text-muted\">January 1, 2022</div>\n");
      out.write("                                    <h2 class=\"card-title h4\">Post Title</h2>\n");
      out.write("                                    <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>\n");
      out.write("                                    <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"col-lg-6\">\n");
      out.write("                            <!-- Blog post-->\n");
      out.write("                            <div class=\"card mb-4\">\n");
      out.write("                                <a href=\"#!\"><img class=\"card-img-top\" src=\"https://dummyimage.com/700x350/dee2e6/6c757d.jpg\" alt=\"...\" /></a>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"small text-muted\">January 1, 2022</div>\n");
      out.write("                                    <h2 class=\"card-title h4\">Post Title</h2>\n");
      out.write("                                    <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla.</p>\n");
      out.write("                                    <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                            <!-- Blog post-->\n");
      out.write("                            <div class=\"card mb-4\">\n");
      out.write("                                <a href=\"#!\"><img class=\"card-img-top\" src=\"https://dummyimage.com/700x350/dee2e6/6c757d.jpg\" alt=\"...\" /></a>\n");
      out.write("                                <div class=\"card-body\">\n");
      out.write("                                    <div class=\"small text-muted\">January 1, 2022</div>\n");
      out.write("                                    <h2 class=\"card-title h4\">Post Title</h2>\n");
      out.write("                                    <p class=\"card-text\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Reiciendis aliquid atque, nulla? Quos cum ex quis soluta, a laboriosam.</p>\n");
      out.write("                                    <a class=\"btn btn-primary\" href=\"#!\">Read more →</a>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Pagination-->\n");
      out.write("                    <nav aria-label=\"Pagination\">\n");
      out.write("                        <hr class=\"my-0\" />\n");
      out.write("                        <ul class=\"pagination justify-content-center my-4\">\n");
      out.write("                            <li class=\"page-item disabled\"><a class=\"page-link\" href=\"#\" tabindex=\"-1\" aria-disabled=\"true\">Newer</a></li>\n");
      out.write("                            <li class=\"page-item active\" aria-current=\"page\"><a class=\"page-link\" href=\"#!\">1</a></li>\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#!\">2</a></li>\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#!\">3</a></li>\n");
      out.write("                            <li class=\"page-item disabled\"><a class=\"page-link\" href=\"#!\">...</a></li>\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#!\">15</a></li>\n");
      out.write("                            <li class=\"page-item\"><a class=\"page-link\" href=\"#!\">Older</a></li>\n");
      out.write("                        </ul>\n");
      out.write("                    </nav>\n");
      out.write("                </div>\n");
      out.write("                <!-- Side widgets-->\n");
      out.write("                <div class=\"col-lg-4\">\n");
      out.write("                    <!-- Search widget-->\n");
      out.write("                    <div class=\"card mb-4\">\n");
      out.write("                        <div class=\"card-header\">Search</div>\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <div class=\"input-group\">\n");
      out.write("                                <input class=\"form-control\" type=\"text\" placeholder=\"Enter search term...\" aria-label=\"Enter search term...\" aria-describedby=\"button-search\" />\n");
      out.write("                                <button class=\"btn btn-primary\" id=\"button-search\" type=\"button\">Go!</button>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Categories widget-->\n");
      out.write("                    <div class=\"card mb-4\">\n");
      out.write("                        <div class=\"card-header\">Categories</div>\n");
      out.write("                        <div class=\"card-body\">\n");
      out.write("                            <div class=\"row\">\n");
      out.write("                                <div class=\"col-sm-6\">\n");
      out.write("                                    <ul class=\"list-unstyled mb-0\">\n");
      out.write("                                        <li><a href=\"#!\">Web Design</a></li>\n");
      out.write("                                        <li><a href=\"#!\">HTML</a></li>\n");
      out.write("                                        <li><a href=\"#!\">Freebies</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                                <div class=\"col-sm-6\">\n");
      out.write("                                    <ul class=\"list-unstyled mb-0\">\n");
      out.write("                                        <li><a href=\"#!\">JavaScript</a></li>\n");
      out.write("                                        <li><a href=\"#!\">CSS</a></li>\n");
      out.write("                                        <li><a href=\"#!\">Tutorials</a></li>\n");
      out.write("                                    </ul>\n");
      out.write("                                </div>\n");
      out.write("                            </div>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <!-- Side widget-->\n");
      out.write("                    <div class=\"card mb-4\">\n");
      out.write("                        <div class=\"card-header\">Side Widget</div>\n");
      out.write("                        <div class=\"card-body\">You can put anything you want inside of these side widgets. They are easy to use, and feature the Bootstrap 5 card component!</div>\n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("        <!-- Footer-->\n");
      out.write("        <footer class=\"py-5 bg-dark\">\n");
      out.write("            <div class=\"container\"><p class=\"m-0 text-center text-white\">Copyright &copy; Your Website 2022</p></div>\n");
      out.write("        </footer>\n");
      out.write("        <!-- Bootstrap core JS-->\n");
      out.write("        <!-- <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js\"></script> -->\n");
      out.write("        <script src=\"/resources/bootstrap-5.1.3-dist/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <!-- Core theme JS-->\n");
      out.write("        <script src=\"/resources/templates/js/scripts.js\"></script>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
